version: '3'
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflow_part
    container_name: ocr_captcha_airflow
    ports:
      - "8080:8080"
  
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flask_part
    container_name: ocr_captcha_flask
    ports:
      - "8000:8000"